version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  web:
    build:
      target: dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL_CACHING: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/1
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
volumes:
  postgres:
